# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6854c92793b984417b75fde1781f43efb75cc8012d5f706dee056c102d016a7a1ae567b9f975a3a6ca12fa4dd2472852199be49c6dbc2159733693efcd9c376c

test:
  secret_key_base: 63c6d1f7f1d52e2d409e4c4755ee9fd0f1bbeab35c133a09eafc216d97ccd0cbc002160a924a1bc83fa17cab948d6b387811eb7979568dad91bf665a852c50dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
